CREATE TABLE users
(
    id  INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    login    VARCHAR(50)                                          NOT NULL,
    name     VARCHAR(50)                                          NOT NULL,
    email    VARCHAR(50)                                          NOT NULL,
    birthday DATE                                                 NOT NULL,
);

CREATE TABLE films
(
    id      INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name         VARCHAR(50)                                          NOT NULL,
    description  VARCHAR(250)                                         NOT NULL,
    local_date   DATE                                                 NOT NULL,
    duration     INTEGER                                              NOT NULL,
    like_by_user INTEGER                                              NOT NULL,
    genres       VARCHAR(50)                                          NOT NULL,
    mpa          VARCHAR(50)                                          NOT NULL,
    rating_id    INTEGER REFERENCES ratings (rating_id)
);

CREATE TABLE likes
(
    film_id INTEGER REFERENCES films (id),
    user_id INTEGER REFERENCES users (id),
    CONSTRAINT pk_likes PRIMARY KEY (film_id, user_id)
);

CREATE TABLE friends
(
    film_id INTEGER REFERENCES films (film_id),
    user_id INTEGER REFERENCES users (user_id),
    status  VARCHAR(50) NOT NULL,
    CONSTRAINT pk_friends PRIMARY KEY (film_id, user_id)
);

CREATE TABLE ratings
(
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name      VARCHAR(50)
);

CREATE TABLE genres
(
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name     VARCHAR(50)
);

CREATE TABLE film_genres
(
    film_id  INTEGER REFERENCES films (film_id),
    genre_id INTEGER REFERENCES genres (genre_id),
    CONSTRAINT pk_film_genres PRIMARY KEY (film_id, genre_id)
);