CREATE TABLE users
(
    id       INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    login    VARCHAR(50)                                          NOT NULL,
    name     VARCHAR(50)                                          NOT NULL,
    email    VARCHAR(50)                                          NOT NULL,
    birthday DATE                                                 NOT NULL
);

CREATE TABLE films
(
    id           INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name         VARCHAR(50)                                          NOT NULL,
    description  VARCHAR(250),
    release_date DATE                                                 NOT NULL,
    duration     INTEGER                                              NOT NULL,
    rate         INTEGER                                              NOT NULL,
    rating    INTEGER REFERENCES ratings (id)
);

CREATE TABLE likes
(
    film_id INTEGER REFERENCES films (id),
    user_id INTEGER REFERENCES users (id),
    rate    INTEGER DEFAULT 10,
    CONSTRAINT pk_likes PRIMARY KEY (film_id, user_id)
);

CREATE TABLE friends
(
    user_id   INTEGER REFERENCES users (id) ON DELETE NO ACTION,
    friend_id INTEGER REFERENCES users (id) ON DELETE NO ACTION,
    status    VARCHAR(50) NOT NULL,
    CONSTRAINT pk_friends PRIMARY KEY (user_id, friend_id)
);

CREATE TABLE ratings
(
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50)
);

CREATE TABLE genres
(
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50)
);

CREATE TABLE film_genres
(
    film_id  INTEGER REFERENCES films (id),
    genre_id INTEGER REFERENCES genres (id),
    CONSTRAINT pk_film_genres PRIMARY KEY (film_id, genre_id)
);